name: Build
# on: [push, pull_request]
on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '*'
  pull_request:
    branches-ignore:
      - main
  workflow_call:

jobs:
  build:
    runs-on: linux
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -Dorg.gradle.console=plain
