name: Build
# on: [push, pull_request]
on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '*'
  pull_request:
    branches-ignore:
      - main
  workflow_call:

jobs:
  build:
    runs-on: linux
    steps:
    - uses: ./.gitea/actions/build/action.yml
      with:
        java-version: 21
