name: Build and Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: linux
    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -Dorg.gradle.console=plain

    - name: Publish to GitHub Packages
      run: ./gradlew publish -Dorg.gradle.console=plain
      env:
        accessToken: ${{ secrets.DEPLOY_TOKEN }}
