name: Publish
on:
  push:
    branches:
      - main
      - feature/#10-add-changelog-generation
    tags:
      - '*'

jobs:
  build:
    runs-on: linux
    steps:
      - uses: actions/checkout@v4

      - uses: ./.gitea/actions/build
        with:
          java-version: 21
    
  publish:
    runs-on: linux
    steps:
    - uses: actions/checkout@v4
    - uses: ./.gitea/actions/gradle
      with:
        command: publish 
      env:
        accessToken: ${{ secrets.DEPLOY_TOKEN }}