name: Publish
on:
  push:
    branches:
      - main
      - feature/#10-add-changelog-generation
    tags:
      - '*'

jobs:
  build:
    runs-on: linux
    steps:
      - uses: ./.gitea/actions/build@feature/#10-add-changelog-generation
        with:
          java-version: 21
    
  publish:
    runs-on: linux
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Publish to GitHub Packages
      run: ./gradlew publish -Dorg.gradle.console=plain
      env:
        accessToken: ${{ secrets.DEPLOY_TOKEN }}