name: Publish
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: linux
    steps:
      - uses: actions/checkout@v4
      - uses: ./.gitea/actions/gradle
        with:
          command: publish 
        env:
          accessToken: ${{ secrets.DEPLOY_TOKEN }}
          GITTEA_GITHUB_TOKEN: ${{ secrets.GITTEA_GITHUB_TOKEN }}
          GITTEA_GITHUB_ACTOR: ${{ secrets.GITTEA_GITHUB_ACTOR }}
