name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    
  publish:
    runs-on: linux
    steps:
    - uses: actions/checkout@v2

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Publish to GitHub Packages
      run: ./gradlew publish -Dorg.gradle.console=plain
      env:
        accessToken: ${{ secrets.DEPLOY_TOKEN }}