name: Publish
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    uses: ./.gitea/workflows/build.yaml
    
  publish:
    runs-on: linux
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Publish to GitHub Packages
      run: ./gradlew publish -Dorg.gradle.console=plain
      env:
        accessToken: ${{ secrets.DEPLOY_TOKEN }}